<a href="https://colab.research.google.com/github/Carlosjara01/Inteligencia-Artificial/blob/main/normalizacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instalar e importar librerías

In [1]:
# Librerías principales para trabajar con datos
import pandas as pd
import numpy as np

# Librerías para normalización
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Librería para descargar el archivo limpio
from google.colab import files

Subir el dataset

In [2]:
# Esta celda permite subir el archivo CSV desde tu computadora
uploaded = files.upload()

Saving sales_data_sample.csv to sales_data_sample.csv

Cargar el dataset

In [3]:
# Cambia el nombre si tu archivo tiene otro nombre
nombre_archivo = "sales_data_sample.csv"

# Cargar el dataset
# encoding="latin1" ayuda cuando el CSV tiene caracteres especiales
df = pd.read_csv(nombre_archivo, encoding="latin1")

# Mostrar las primeras filas
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

Revisar tamaño y estructura

In [4]:
# Cantidad de filas y columnas
print("Filas y columnas:", df.shape)

# Mostrar nombres de columnas
print("\nColumnas del dataset:")
print(df.columns.tolist())

# Ver tipos de datos
print("\nTipos de datos:")
print(df.dtypes)

Filas y columnas: (2823, 25)

Columnas del dataset:
['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER', 'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE', 'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE', 'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'DEALSIZE']

Tipos de datos:
ORDERNUMBER           int64
QUANTITYORDERED       int64
PRICEEACH           float64
ORDERLINENUMBER       int64
SALES               float64
ORDERDATE            object
STATUS               object
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE          object
MSRP                  int64
PRODUCTCODE          object
CUSTOMERNAME         object
PHONE                object
ADDRESSLINE1         object
ADDRESSLINE2         object
CITY                 object
STATE                object
POSTALCODE           object
COUNTRY              object
TERRITORY            object
CONTACTLASTNAME      object
CONTACTFIRSTNAME     object
DEALSIZE             object
dtype: object

Revisar valores nulos

In [5]:
# Ver cantidad de valores nulos por columna
print("Valores nulos por columna:")
print(df.isnull().sum())

Valores nulos por columna:
ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

Crear una copia del dataset

In [6]:
# Creamos una copia para trabajar sin dañar el dataset original
df_limpio = df.copy()

Limpiar espacios en textos

In [7]:
# Elimina espacios innecesarios en columnas de texto
for columna in df_limpio.select_dtypes(include=["object"]).columns:
    df_limpio[columna] = df_limpio[columna].astype(str).str.strip()

Convertir fechas si existen

In [8]:
# Intentamos convertir columnas que tengan la palabra DATE en formato fecha
for columna in df_limpio.columns:
    if "DATE" in columna.upper():
        df_limpio[columna] = pd.to_datetime(df_limpio[columna], errors="coerce")
        print(f"Columna convertida a fecha: {columna}")

Columna convertida a fecha: ORDERDATE

Crear columnas útiles desde fechas

In [9]:
# Si existe ORDERDATE, creamos columnas de año, mes y día
if "ORDERDATE" in df_limpio.columns:
    df_limpio["ORDER_YEAR"] = df_limpio["ORDERDATE"].dt.year
    df_limpio["ORDER_MONTH"] = df_limpio["ORDERDATE"].dt.month
    df_limpio["ORDER_DAY"] = df_limpio["ORDERDATE"].dt.day

Rellenar valores nulos

In [10]:
# Separar columnas numéricas y categóricas
columnas_numericas = df_limpio.select_dtypes(include=["int64", "float64"]).columns
columnas_categoricas = df_limpio.select_dtypes(include=["object"]).columns

# Rellenar nulos numéricos con el promedio
for columna in columnas_numericas:
    df_limpio[columna] = df_limpio[columna].fillna(df_limpio[columna].mean())

# Rellenar nulos categóricos con "Desconocido"
for columna in columnas_categoricas:
    df_limpio[columna] = df_limpio[columna].fillna("Desconocido")

# Verificar nuevamente nulos
df_limpio.isnull().sum()

ORDERNUMBER         0
QUANTITYORDERED     0
PRICEEACH           0
ORDERLINENUMBER     0
SALES               0
ORDERDATE           0
STATUS              0
QTR_ID              0
MONTH_ID            0
YEAR_ID             0
PRODUCTLINE         0
MSRP                0
PRODUCTCODE         0
CUSTOMERNAME        0
PHONE               0
ADDRESSLINE1        0
ADDRESSLINE2        0
CITY                0
STATE               0
POSTALCODE          0
COUNTRY             0
TERRITORY           0
CONTACTLASTNAME     0
CONTACTFIRSTNAME    0
DEALSIZE            0
ORDER_YEAR          0
ORDER_MONTH         0
ORDER_DAY           0
dtype: int64

Seleccionar columnas numéricas para normalizar

In [11]:
# Volvemos a detectar columnas numéricas después de la limpieza
columnas_numericas = df_limpio.select_dtypes(include=["int64", "float64"]).columns

print("Columnas numéricas que se pueden normalizar:")
print(columnas_numericas.tolist())

Columnas numéricas que se pueden normalizar:
['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER', 'SALES', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'MSRP']

. Normalización con StandardScaler

In [12]:
# StandardScaler transforma los datos para que tengan:
# media cercana a 0 y desviación estándar cercana a 1

scaler = StandardScaler()

# Creamos una copia para no perder los valores originales
df_normalizado = df_limpio.copy()

# Aplicamos normalización solo a columnas numéricas
df_normalizado[columnas_numericas] = scaler.fit_transform(df_limpio[columnas_numericas])

# Mostrar resultado
df_normalizado.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,ORDER_YEAR,ORDER_MONTH,ORDER_DAY
0,-1.647947,-0.522891,0.596978,-1.057059,-0.370825,2003-02-24,Shipped,-1.427039,-1.392909,-1.16517,...,NY,10022,USA,nan,Yu,Kwai,Small,2003,2,24
1,-1.495888,-0.112201,-0.114450,-0.347015,-0.427897,2003-05-07,Shipped,-0.596243,-0.572337,-1.16517,...,nan,51100,France,EMEA,Henriot,Paul,Small,2003,5,7
2,-1.354689,0.606505,0.549384,-1.057059,0.179443,2003-07-01,Shipped,0.234553,-0.025289,-1.16517,...,nan,75508,France,EMEA,Da Cunha,Daniel,Medium,2003,7,1
3,-1.235214,1.017195,-0.019759,-0.110334,0.104701,2003-08-25,Shipped,0.234553,0.248235,-1.16517,...,CA,90003,USA,nan,Young,Julie,Medium,2003,8,25
4,-1.083154,1.427884,0.810158,1.783116,0.896740,2003-10-10,Shipped,1.065350,0.795284,-1.16517,...,CA,nan,USA,nan,Brown,Julie,Medium,2003,10,10

Guardar dataset normalizado

In [13]:
# Guardar el dataset limpio y normalizado
nombre_salida = "dataset_limpio_normalizado.csv"

df_normalizado.to_csv(nombre_salida, index=False, encoding="utf-8-sig")

print("Dataset guardado correctamente:", nombre_salida)

Dataset guardado correctamente: dataset_limpio_normalizado.csv

Descargar el dataset limpio

In [14]:
# Descargar el archivo a tu computadora
files.download(nombre_salida)

Verificar resultado final

In [15]:
print("Dataset original:", df.shape)
print("Dataset limpio y normalizado:", df_normalizado.shape)

df_normalizado.head()

Dataset original: (2823, 25)
Dataset limpio y normalizado: (2823, 28)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,ORDER_YEAR,ORDER_MONTH,ORDER_DAY
0,-1.647947,-0.522891,0.596978,-1.057059,-0.370825,2003-02-24,Shipped,-1.427039,-1.392909,-1.16517,...,NY,10022,USA,nan,Yu,Kwai,Small,2003,2,24
1,-1.495888,-0.112201,-0.114450,-0.347015,-0.427897,2003-05-07,Shipped,-0.596243,-0.572337,-1.16517,...,nan,51100,France,EMEA,Henriot,Paul,Small,2003,5,7
2,-1.354689,0.606505,0.549384,-1.057059,0.179443,2003-07-01,Shipped,0.234553,-0.025289,-1.16517,...,nan,75508,France,EMEA,Da Cunha,Daniel,Medium,2003,7,1
3,-1.235214,1.017195,-0.019759,-0.110334,0.104701,2003-08-25,Shipped,0.234553,0.248235,-1.16517,...,CA,90003,USA,nan,Young,Julie,Medium,2003,8,25
4,-1.083154,1.427884,0.810158,1.783116,0.896740,2003-10-10,Shipped,1.065350,0.795284,-1.16517,...,CA,nan,USA,nan,Brown,Julie,Medium,2003,10,10